# These are supported funding model platforms

custom: ['https://www.fiverr.com/creativitas/design-presentation-website-for-marketing-product','https://www.fiverr.com/creativitas/design-a-website-blog-with-our-cool-template-flat-file-cms','https://www.fiverr.com/creativitas/design-your-modern-website-using-jekyll']
